config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups, except: [:edit, :update] do
    member do
      get 'invite'
      post 'invite', to: 'groups#send_invites'
      get 'join'
    end
  end

  resources :salaries, only: [:new, :create, :update, :destroy]

  resources :users, only: [:new, :create] do
    member do
      get 'verification'
      get 'resend_verification'
      get 'verify'
      get 'settings'
    end
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '/graphs' do
    controller :graphs do
      get ':group_id/distribution(/:title)' => :distribution, as: 'distribution_graph'
      get ':group_id/scatter(/:title)' => :scatter, as: 'scatter_graph'
      get ':group_id/title-medians' => :title_medians, as: 'title_medians_graph'
    end
  end
end

app/views/partials/_flash_messages.html.erb
<% classes ||= [] %>

<% if flash[:alert].present? %>
  <div class="<%= (classes + %w(alert alert-danger)).join(' ') %>" role="alert">
    <p><%= flash[:alert] %> <i class="fa fa-close"></i></p>
  </div>
<% end %>
<% if flash[:notice].present? %>
  <div class="<%= (classes + %w(alert alert-info)).join(' ') %>" role="alert">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

app/views/partials/_groups_sidebar.html.erb
<% groups ||= [] %>

<!-- Groups Sidebar -->
<%= content_for :groups_sidebar do %>
  <div class="groups-list">
    <h4>Groups</h4>
    <ul class="multiple-select">
      <% groups.each do |this_group| %>
        <%= content_tag :li, class: group_selected_class(group == this_group) do %>
          <%= link_to truncate(this_group.name, length: 22), group_path(this_group) %>
        <% end %>
      <% end %>
    </ul>
    <div class="create-group-btn">
      <a href="#"><i class="fa fa-plus"></i> Create New</a>
    </div>
  </div>
<% end %>

app/views/partials/_header.html.erb
<header>
  <h2 class="logo">PaySymmetry</h2>
  <% if @user.present? %>
    <div class="dropdown">
      <a href="#" class="username dropdown-toggle" data-toggle="dropdown">
        <%= @user.username %> <i class="fa fa-angle-down"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <p>Logged in as<br><span class="email"><%= @user.email %></p>
        <div class="divider"></div>
        <ul class="multiple-select">
          <li>
            <a class="dropdown-item" href="#">Settings</a>
          </li>
          <li>
          <%= link_to "Log Out", logout_path, method: :delete,
                class: "dropdown-item" %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</header>