config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups, except: [:edit, :update] do
    member do
      get 'invite'
      post 'invite', to: 'groups#send_invites'
      get 'join'
    end
  end

  resources :salaries, only: [:new, :create, :update, :destroy]

  resources :users, only: [:new, :create] do
    member do
      get 'verification'
      get 'resend_verification'
      get 'verify'
      get 'settings'
    end
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '/graphs' do
    controller :graphs do
      get ':group_id/distribution(/:title)' => :distribution, as: 'distribution_graph'
      get ':group_id/scatter(/:title)' => :scatter, as: 'scatter_graph'
      get ':group_id/title-medians' => :title_medians, as: 'title_medians_graph'
    end
  end
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id                :integer          not null, primary key
#  name              :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  invitations_count :integer          default(0)
#

class Group < ActiveRecord::Base
  validates :name, presence: true
  has_many :salaries, dependent: :destroy
  has_many :users, through: :salaries

  def titles
    Salary.where(group_id: id).distinct.pluck(:title)
  end

  def empty?
    users.count == 0
  end

  # Returns a hash of salary collection objects keyed by title.
  def salaries_by_title
    groupings = salaries.group_by(&:title)
    groupings.merge!(groupings) do |title, salaries|
      Statistics::TitleGrouping.new(salaries)
    end
  end

  def lowest_paying_title
    titles = titles_by_average_pay
    [titles.first["title"], titles.first["avg"].to_i]
  end

  def highest_paying_title
    titles = titles_by_average_pay
    [titles.last["title"], titles.last["avg"].to_i]
  end

  def statistics
    Statistics::SalaryCollection.new(self)
  end

  protected
  def sorted_salaries(key, desc = false)
    if desc
      salaries.order({ key => :desc })
    else
      salaries.order(key)
    end
  end

  def titles_by_average_pay
    titles = Group.connection.select_all <<-SQL
      SELECT title, AVG(annual_pay) AS avg
      FROM salaries
      WHERE group_id = #{id.to_i}
      GROUP BY title
      ORDER BY avg;
    SQL
  end
end

app/controllers/groups_controller.rb
class GroupsController < GroupAccessController
  skip_before_action :authorize_group, only: [:index,
                                              :new,
                                              :create,
                                              :join]

  def index
    redirect_group = Group.joins(:salaries)
                          .where(salaries: { user_id: @user.id })
                          .order(:name)
                          .first

    if redirect_group.present?
      redirect_to group_path(redirect_group.id)
    end
  end
  
  def show
    @groups = Group.joins(:salaries)
                   .where(salaries: { user_id: @user.id })
                   .order(:name)

    @salary = @group.salaries.where(user_id: @user.id).first
    @salaries_by_title = @group.salaries_by_title

    @title = params[:title] if params[:title].present?

    if @title
      @count = @salaries_by_title[@title].count
    else
      @count = @group.salaries.count
    end
  end

  def new
  end

  def create
    group = Group.new(name: params[:group_name])
    group.save!

    onboard_user_to_group group.id
  end

  # invitations
  def invite
  end

  def send_invites
    if params[:emails]
      emails = params[:emails].split(',').map { |email| email.strip }
      orig_count = emails.count

      existing_members = @group.users.where("email in (?)", emails)
                                     .pluck(:email)
      emails -= existing_members

      if emails.count > 0
        @group.invitations_count += emails.count
        @group.save!

        UserMailer.invite_email(@group, emails).deliver_later
      end

      if orig_count == 1
        notice = "#{orig_count} invitation sent."
      else
        notice = "#{orig_count} invitations sent."
      end

      redirect_to group_path(@group), notice: notice
    else
      head 400
    end
  end

  def join
    onboard_user_to_group params[:id]
  end

  protected
  def onboard_user_to_group(group_id)
    session[:group_to_join_id] = group_id
    redirect_to new_salary_path
  end
end

app/views/groups/index.html.erb
<!-- Groups Sidebar -->
<%= content_for :groups_sidebar do %>
  <%= render partial: 'partials/groups_sidebar' %>
<% end %>

<div class="center-div spaced-body">
  <h3>You're not yet in any groups.</h3>
  <p>If you've been invited to a group, accept the invitation <br/>by clicking on
  the <i class="fa fa-envelope"></i> icon in the top right.</p>
  <p>You can also create a new group by using the "Create New" <br/>button on the
  left.</p>
</div>

app/views/groups/invite.html.erb
<h3>Invite Coworkers</h3>
<div class="spaced">
  <p>Who would you like to invite to be a part of your group?</p>
  <p>Enter their email addresses below, separated by commas:</p>
</div>

<%= form_tag controller: "groups", action: "send_invites" do %>
  <%= text_area_tag :emails, "", size: "48x8" %>
  <div class="double-spaced">
    <%= submit_tag "Invite", class: %w{ btn btn-default } %>
    <%= link_to "Skip", group_path(@group), class: %w{ btn btn-default } %>
  </div>
<% end %>

app/views/groups/new.html.erb
<%= form_tag controller: "groups", action: "create" do %>
  <%= label_tag :name_label, "Group Name" %>
  <%= text_field_tag :group_name %>
  <p class="note">For example, <em>Acme Co. Employees</em></p>

  <div class="double-spaced">
    <%= submit_tag "Continue", class: %w{ btn btn-default } %>
  </div>
<% end %>

app/views/groups/show.html.erb
<!-- Groups Sidebar -->
<%= content_for :groups_sidebar do %>
  <div class="groups-list">
    <h4>Groups</h4>
    <ul class="multiple-select">
      <% @groups.each do |group| %>
        <%= content_tag :li, class: group_selected_class(@group == group) do %>
          <%= link_to truncate(group.name, length: 22), group_path(group) %>
        <% end %>
      <% end %>
    </ul>
    <div class="create-group-btn">
      <a href="#"><i class="fa fa-plus"></i> Create New</a>
    </div>
  </div>
<% end %>

<!-- Personal Info Sidebar -->
<aside class="info-sidebar box">
  <h3 class="heading">You <i class="fa fa-pencil"></i></h3>
  <ul class="info">
    <li>Title</li>
    <li><%= cap(@salary.title) %></li>
    <li>Salary</li>
    <li><%= dollar(@salary.annual_pay) %></li>
  </ul>
  <a href="#" class="btn-solid">Invite Members</a>
  <a href="#" class="btn-solid">Leave Group</a>
</aside>

<!-- Main Content -->
<div class="sections-holder">
  <section class="company-section box">
    <div class="company-title-row">
      <h2 class="company-heading"><%= @group.name %></h2>
      <div class="company-util dropdown">
        <a href="#" class="title-select dropdown-toggle" data-toggle="dropdown">
          <%= current_title %> <i class="fa fa-angle-down"></i>
        </a>
        <span><i class="fa fa-user"></i> <%= @count %></span>
        <div class="dropdown-menu dropdown-menu-right">
          <ul class="multiple-select">
            <li>
              <% url = group_path(id: @group.id) %>
              <a class="dropdown-item" href="<%= url %>">All Titles</a>
            </li>
            <div class="divider"></div>
            <% @salaries_by_title.keys.sort.each do |title| %>
              <li>
                <% url = group_path(id: @group.id, title: title) %>
                <a class="dropdown-item" href="<%= url %>"><%= cap(title) %></a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <table class="stat-summary">
      <tr class="stat-numbers">
        <% title_stats = @salaries_by_title[@salary.title].statistics %>
        <td><%= title_stats.count %></td>
        <td class="emphasize"><%= dollar(title_stats.median_annual_pay, short: true) %></td>
        <td><%= title_stats.rank_of(@salary) %></td>
      </tr>
      <tr class="stat-captions">
        <td class="caption">Members<br>with Your Title</td>
        <td class="caption">Median Salary<br>for Your Title</td>
        <td class="caption">Your Rank<br>within Your Title</td>
      </tr>
    </table>
  </section>

  <%= render layout: 'layouts/section', locals: { caption: "Salaries (#{current_title})" } do %>
    <table class="salary-table">
      <thead>
        <tr>
          <th class="caption">Title</th>
          <th class="caption">Salary</th>
        </tr>
      </thead>
      <% @salaries_by_title.keys.sort.each do |title| %>
        <% next if @title && title != @title %>
        <% grouping = @salaries_by_title[title] %>
        <tbody>
          <tr>
            <td><i class="fa fa-angle-down"></i> <%= cap(title) %></td>
            <td><i class="fa fa-user"></i> <%= grouping.salaries.count %>
          </tr>
          <% grouping.salaries.each do |salary| %>
            <tr>
              <td><%= cap(salary.title) %></td>
              <td><%= dollar(salary.annual_pay) %></td>
            </tr>
          <% end %>
        </tbody>
      <% end %>
    </table>
  <% end %>

  <%= render layout: 'layouts/section', 
             locals: { caption: "Salary Distribution (#{current_title})" } do %>
    <div class="canvas-holder">
      <%= column_chart(distribution_graph_path(group_id: @group.id, title: @title),
                       xtitle: "Salary Bucket",
                       ytitle: "Count",
                       colors: ["#cdd"],
                       library: get_library()) %>
    </div>
  <% end %>

  <%= render layout: 'layouts/section', 
             locals: { caption: "Salary Scatter Plot (#{current_title})" } do %>
    <div class="canvas-holder">
      <%= scatter_chart(scatter_graph_path(group_id: @group.id, title: @title), 
                        xtitle: "Salary Rank (Ascending)",
                        ytitle: "Salary",
                        colors: ["#cdd"],
                        library: get_library()) %>
    </div>
  <% end %>

  <% unless @title %>
    <%= render layout: 'layouts/section', 
               locals: { caption: "Median Salary By Title" } do %>
      <div class="canvas-holder">
        <%= bar_chart(title_medians_graph_path(group_id: @group.id),
                      xtitle: "Salary",
                      ytitle: "Title",
                      colors: ["#cdd"],
                      library: get_library()) %>
      </div>
    <% end %>
  <% end %>
</div>