config/routes.rb
Rails.application.routes.draw do
  root "groups#index"

  resources :groups, except: [:edit, :update] do
    member do
      get 'invite'
      post 'invite', to: 'groups#send_invites'
      get 'join'
    end
  end

  resources :salaries, only: [:new, :create, :update, :destroy]

  resources :users, only: [:new, :create] do
    member do
      get 'verification'
      get 'resend_verification'
      get 'verify'
      get 'settings'
    end
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '/graphs' do
    controller :graphs do
      get ':group_id/distribution(/:title)' => :distribution, as: 'distribution_graph'
      get ':group_id/scatter(/:title)' => :scatter, as: 'scatter_graph'
      get ':group_id/title-medians' => :title_medians, as: 'title_medians_graph'
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  email             :string(255)
#  password_digest   :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  verified          :boolean          default(FALSE)
#  verification_code :string(255)
#

class User < ActiveRecord::Base
  validates :email, presence: true, format: { with: /\A[^@]+@[^@]+\z/ }
  has_many :salaries, dependent: :destroy
  has_many :groups, through: :salaries
  has_secure_password

  def alert_message
    if errors[:email].any?
      "You must enter a valid email address."
    elsif errors[:password].any?
      "You must enter a valid password."
    elsif errors[:password_confirmation].any?
      "You did not enter matching passwords."
    else
      ""
    end
  end

  def username
    email.split('@').first
  end
end

app/controllers/users_controller.rb
require 'securerandom'

class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create]
  skip_before_action :verification_check, 
    only: [:verification, :resend_verification, :verify]

  def new
  end

  def create
    @email = params[:email]
    password = params[:password]
    password_confirm = params[:password_confirm]

    user = User.new(email: @email,
                    password: password,
                    password_confirmation: password_confirm,
                    verification_code: random_verification_code)
    
    begin
      if user.save
        session[:user_id] = user.id
        send_verification_email_to user
        redirect_to verification_user_path(user)
      else
        redirect_to new_user_path, alert: user.alert_message
      end
    rescue ActiveRecord::RecordNotUnique 
      alert = "An account with that email address already exists."
      redirect_to new_user_path, alert: alert
    end
  end

  # email verificiation
  def verification
  end

  def resend_verification
    unless @user.verification_code
      @user.verification_code = random_verification_code 
      @user.save!
    end

    send_verification_email_to @user

    notice = "Email sent. Please be sure to check your spam folder."
    redirect_to verification_user_path(@user), notice: notice
  end

  def verify
    if params[:code] and params[:code] == @user.verification_code
      @verified = true
      @user.verified = true
      @user.save!

      if session[:group_to_join_id].present?
        @group = Group.find(session[:group_to_join_id])
      end
    else
      @verified = false
    end
  end

  protected
  def random_verification_code
    SecureRandom.hex(12)
  end

  def send_verification_email_to(user)
    UserMailer.verification_email(user).deliver_later
  end
end

app/views/users/new.html.erb
<section class="box form-box">
  <p class="caption">Create an Account</p>
  <%= form_tag controller: "users", action: "create" do %>
    <div class="input-group">
      <%= label_tag :email_label, "Email" %>
      <%= email_field_tag :email, nil, class: "input-block", placeholder: "example@domain.com" %>
    </div>
    <div class="input-group">
      <%= label_tag :password_label, "Password" %>
      <%= password_field_tag :password, nil, class: "input-block", placeholder: "Enter a password" %>
    </div>
    <div class="input-group">
      <%= label_tag :password_confirm_label, "Password Confirmation" %>
      <%= password_field_tag :password_confirm, nil, class: "input-block", placeholder: "Enter the same password" %>
    </div>
    <div class="input-group">
      <button type="submit" class="btn btn-solid">
        <p>Create Account <i class="fa fa-angle-right"></i></p>
      </button>
    </div>
  <% end %>
</section>

app/views/users/settings.html.erb
<p>Wow. Such settings. Much options. Wow.</p>

app/views/users/verification.html.erb
<section class="box form-box spaced-body">
  <p class="caption">Verify Your Email Address</p>
  <h3>Great! Your account is almost ready.</h3>
  <p>We've sent an email to "<%= @user.email %>" with the link you need to verify
   your email address. Clicking on that link will take you to the next step.</p>
  <p>If you don't see an email from us, check your spam folder. You can also
  resend the email below.</p>
  <div class="input-group">
    <%= link_to "Resend Email", resend_verification_user_path(@user),
        class: %w{ btn btn-solid } %>
  </div>
</section>

app/views/users/verify.html.erb
<section class="box form-box spaced-body">
  <% if @verified %>
    <p class="caption">Email Verification Success</p>
    <h3>You're all set!</h3>
    <p>We've verified your email address and you're ready to go.</p>
    <div class="input-group">
      <%= link_to "Get Started", groups_path(@user),
          class: %w{ btn btn-solid } %>
    </div>
  <% else %>
    <p class="caption">Email Verification Failure</p>
    <h3>Uh Oh</h3>
    <p>If you're seeing this page, you've tried to verify your email address with
    a code that we don't recognize. Please check 
    your inbox. We may have sent you an email more recently.</p>
    <p>Please also check that you are logged-in with the correct email address.
    You are currently logged-in as:</p>
    <h4><%= @user.email %></h4>
  <% end %>
</section>